name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x, 22.x, 23.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies with pnpm
      run: pnpm install --frozen-lockfile

    - name: Run the tests with coverage
      run: pnpm run test:coverage 
